services:
  shmavito_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: shoppy
      POSTGRES_PASSWORD: shoppy
      POSTGRES_DB: shmavito
    ports:
      - 15434:5432
    volumes:
      - db-data:/var/lib/postgresql
  shmavito_web:
    build: .
    command: >
      sh -c "/shmavito/wait-for-it.sh shmavito_db:5432 -- python manage.py migrate && python manage.py loaddata data.json && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/shmavito
    ports:
      - "8001:8001"
    depends_on:
      - shmavito_db
volumes:
    db-data:




